name: CI

on: [push]

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Create virtual environment
      run: python3 -m venv env && source env/bin/activate

    - name: Install requirements
      run: pip3 install -r requirements.txt

    - name: Run tests
      run: pytest src/test.py
