name: CI

on: [push]

jobs:

  test:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Set up dependencies
      run: sudo apt-get install python3-venv

    - name: Checkout
      uses: actions/checkout@master

    - name: Create virtual environment
      run: python3 -m venv env

    - name: Set up requirements
      run: source env/bin/activate && pip3 install -r requirements.txt

    - name: Run tests
      run: source env/bin/activate && pytest src/test.py
